image: node:6.9.4
clone:
  depth: full
pipelines:
  default:
    - step:
        caches:
          - node
        name: Deploy to Heroku
        deployment: test
        script: # Modify the commands below to build your repository.
          - npm install
          - npm install --save-dev jest
          - npm test
          - npm run build
